//! 图标 key（Lucide 名称）→ [`IconKind`] 的反向查表。
//!
//! 注册表（`ham_web_core::registry`）只保存 Lucide 名称字符串，让领域数据不必依赖
//! 前端类型；渲染时用本模块换回枚举。映射与 [`IconKind::name`] 互为逆函数，
//! 由 `round_trips_with_name` 测试把守 —— 图标名写错会直接让测试失败。

use super::IconKind;

/// 全部图标 key（按 Lucide 名称排序）。仅用于校验反向映射的完整性。
#[cfg(test)]
pub const ICON_KEYS: &[&str] = &[
  "activity",
  "anchor",
  "arrow-up-down",
  "audio-lines",
  "award",
  "badge-check",
  "battery-charging",
  "battery-low",
  "binary",
  "book-marked",
  "book-open",
  "bookmark",
  "box",
  "building-2",
  "calculator",
  "calendar",
  "camera",
  "case-upper",
  "check",
  "chevron-down",
  "chevron-left",
  "chevron-right",
  "circle",
  "circle-alert",
  "circle-check",
  "circle-check-big",
  "circle-x",
  "clipboard-list",
  "clock",
  "cloud",
  "compass",
  "cpu",
  "credit-card",
  "download",
  "external-link",
  "file-text",
  "filter",
  "flame",
  "gauge",
  "globe",
  "graduation-cap",
  "hammer",
  "headphones",
  "history",
  "house",
  "landmark",
  "layout-grid",
  "list-x",
  "loader-circle",
  "mail",
  "map",
  "menu",
  "messages-square",
  "minus",
  "monitor",
  "moon",
  "mountain",
  "network",
  "orbit",
  "plane",
  "play",
  "plug-zap",
  "plus",
  "radio",
  "radio-tower",
  "refresh-cw",
  "satellite",
  "scale",
  "search",
  "send",
  "settings",
  "shield-alert",
  "shield-x",
  "signal",
  "siren",
  "sliders-horizontal",
  "sparkles",
  "star",
  "sun",
  "sun-medium",
  "timer",
  "trending-up",
  "trophy",
  "tv",
  "type",
  "user",
  "volume-2",
  "waves",
  "waypoints",
  "workflow",
  "wrench",
  "x",
  "zap",
];

/// 按 Lucide 名称查找图标；未知名称回退到 [`IconKind::Circle`]。
#[must_use]
pub fn icon_of(key: &str) -> IconKind {
  match key {
    "activity" => IconKind::Activity,
    "anchor" => IconKind::Anchor,
    "arrow-up-down" => IconKind::ArrowUpDown,
    "audio-lines" => IconKind::AudioLines,
    "award" => IconKind::Award,
    "badge-check" => IconKind::BadgeCheck,
    "battery-charging" => IconKind::BatteryCharging,
    "battery-low" => IconKind::BatteryLow,
    "binary" => IconKind::Binary,
    "book-marked" => IconKind::BookMarked,
    "book-open" => IconKind::BookOpen,
    "bookmark" => IconKind::Bookmark,
    "box" => IconKind::Box,
    "building-2" => IconKind::Building2,
    "calculator" => IconKind::Calculator,
    "calendar" => IconKind::Calendar,
    "camera" => IconKind::Camera,
    "case-upper" => IconKind::CaseUpper,
    "check" => IconKind::Check,
    "chevron-down" => IconKind::ChevronDown,
    "chevron-left" => IconKind::ChevronLeft,
    "chevron-right" => IconKind::ChevronRight,
    "circle" => IconKind::Circle,
    "circle-alert" => IconKind::AlertCircle,
    "circle-check" => IconKind::CheckCircle2,
    "circle-check-big" => IconKind::CheckCircle,
    "circle-x" => IconKind::XCircle,
    "clipboard-list" => IconKind::ClipboardList,
    "clock" => IconKind::Clock,
    "cloud" => IconKind::Cloud,
    "compass" => IconKind::Compass,
    "cpu" => IconKind::Cpu,
    "credit-card" => IconKind::CreditCard,
    "download" => IconKind::Download,
    "external-link" => IconKind::ExternalLink,
    "file-text" => IconKind::FileText,
    "filter" => IconKind::Filter,
    "flame" => IconKind::Flame,
    "gauge" => IconKind::Gauge,
    "globe" => IconKind::Globe,
    "graduation-cap" => IconKind::GraduationCap,
    "hammer" => IconKind::Hammer,
    "headphones" => IconKind::Headphones,
    "history" => IconKind::History,
    "house" => IconKind::Home,
    "landmark" => IconKind::Landmark,
    "layout-grid" => IconKind::LayoutGrid,
    "list-x" => IconKind::ListX,
    "loader-circle" => IconKind::Loader2,
    "mail" => IconKind::Mail,
    "map" => IconKind::Map,
    "menu" => IconKind::Menu,
    "messages-square" => IconKind::MessagesSquare,
    "minus" => IconKind::Minus,
    "monitor" => IconKind::Monitor,
    "moon" => IconKind::Moon,
    "mountain" => IconKind::Mountain,
    "network" => IconKind::Network,
    "orbit" => IconKind::Orbit,
    "plane" => IconKind::Plane,
    "play" => IconKind::Play,
    "plug-zap" => IconKind::PlugZap,
    "plus" => IconKind::Plus,
    "radio" => IconKind::Radio,
    "radio-tower" => IconKind::RadioTower,
    "refresh-cw" => IconKind::RefreshCw,
    "satellite" => IconKind::Satellite,
    "scale" => IconKind::Scale,
    "search" => IconKind::Search,
    "send" => IconKind::Send,
    "settings" => IconKind::Settings,
    "shield-alert" => IconKind::ShieldAlert,
    "shield-x" => IconKind::ShieldX,
    "signal" => IconKind::Signal,
    "siren" => IconKind::Siren,
    "sliders-horizontal" => IconKind::SlidersHorizontal,
    "sparkles" => IconKind::Sparkles,
    "star" => IconKind::Star,
    "sun" => IconKind::Sun,
    "sun-medium" => IconKind::SunMedium,
    "timer" => IconKind::Timer,
    "trending-up" => IconKind::TrendingUp,
    "trophy" => IconKind::Trophy,
    "tv" => IconKind::Tv,
    "type" => IconKind::Type,
    "user" => IconKind::User,
    "volume-2" => IconKind::Volume2,
    "waves" => IconKind::Waves,
    "waypoints" => IconKind::Waypoints,
    "workflow" => IconKind::Workflow,
    "wrench" => IconKind::Wrench,
    "x" => IconKind::X,
    "zap" => IconKind::Zap,
    _ => IconKind::Circle,
  }
}

#[cfg(test)]
mod tests {
  use super::*;

  #[test]
  fn round_trips_with_name() {
    assert!(ICON_KEYS.len() >= 50, "图标数量偏少：{}", ICON_KEYS.len());
    for key in ICON_KEYS {
      assert_eq!(icon_of(key).name(), *key, "图标 {key} 的反向映射不一致");
    }
    // 未知名称回退，不 panic。
    assert_eq!(icon_of("不存在的图标"), IconKind::Circle);
  }
}
