//! 像素图标与精灵的「源数据」：生成器（`sprites.rs`）把它渲染成 `crates/app/src/icons/pixel/*.rs`。
//!
//! 画法：每行一个字符串，一个字符对应一个像素，`.` 为透明。同色相邻像素会被合并成矩形，
//! 输出紧凑的 SVG `path`，运行时零计算。改了这里就跑 `cargo make pixel-sprites`。

/// IconKind 变体 → pixelarticons 的文件名（`None` 表示用下面 [`HAND_ICONS`] 的手绘字符画）。
///
/// 图标集许可证：pixelarticons —— MIT，Copyright (c) 2019 Gerrit Halfmann；
/// 生成物头部也带了这条声明。
pub const ICON_MAP: &[(&str, Option<&str>)] = &[
  ("Settings", Some("settings-cog")),
  ("Search", Some("search")),
  ("X", Some("close")),
  ("ChevronDown", Some("chevron-down")),
  ("Check", Some("check")),
  ("CheckCircle", None),
  ("CheckCircle2", None),
  ("ExternalLink", Some("external-link")),
  ("Loader2", Some("loader")),
  ("XCircle", None),
  ("AlertCircle", Some("warning-diamond")),
  ("RefreshCw", Some("reload")),
  ("Camera", Some("camera")),
  ("Home", Some("home")),
  ("Moon", Some("moon")),
  ("Sun", Some("sun")),
  ("Circle", Some("circle")),
  ("CreditCard", Some("credit-card")),
  ("User", Some("user")),
  ("Download", Some("download")),
  ("Satellite", None),
  ("Menu", Some("menu")),
  ("ClipboardList", Some("clipboard-note")),
  ("Timer", Some("hourglass")),
  ("BookOpen", Some("book-open")),
  ("LayoutGrid", Some("grid-2x2-2")),
  ("Radio", Some("radio")),
  ("AudioLines", Some("audio-waveform")),
  ("Play", Some("play")),
  ("CaseUpper", Some("letter-a")),
  ("BookMarked", Some("notebook")),
  ("RadioTower", None),
  ("Calculator", Some("calculator")),
  ("Globe", Some("earth")),
  ("SlidersHorizontal", Some("sliders-horizontal")),
  ("Binary", Some("binary")),
  ("Gauge", Some("speed-fast")),
  ("Orbit", None),
  ("MessagesSquare", Some("message-text")),
  ("Signal", Some("signal")),
  ("Waves", Some("waves")),
  ("ListX", None),
  ("SunMedium", Some("sun")),
  ("ShieldAlert", Some("shield")),
  ("BadgeCheck", Some("shield")),
  ("Volume2", Some("volume-2")),
  ("Bookmark", Some("bookmark")),
  ("Zap", Some("zap")),
  ("Trophy", Some("trophy")),
  ("Cpu", Some("cpu")),
  ("PlugZap", Some("plug")),
  ("Activity", Some("chart-line")),
  ("BatteryCharging", Some("battery-full")),
  ("Award", Some("crown")),
  ("Map", Some("map")),
  ("Monitor", Some("monitor")),
  ("Siren", Some("siren")),
  ("GraduationCap", None),
  ("Landmark", Some("library")),
  ("Compass", Some("compass")),
  ("Sparkles", Some("sparkles")),
  ("Wrench", Some("tools")),
  ("Send", Some("send")),
  ("History", Some("undo")),
  ("TrendingUp", Some("trending-up")),
  ("Mountain", None),
  ("Hammer", Some("tool-case")),
  ("Mail", Some("mail")),
  ("ShieldX", Some("shield")),
  ("BatteryLow", Some("battery-low")),
  ("Plane", None),
  ("Scale", Some("scale")),
  ("Waypoints", Some("git-branch")),
  ("Cloud", Some("cloud")),
  ("Type", None),
  ("Anchor", Some("anchor")),
  ("Workflow", None),
  ("Headphones", Some("headphone")),
  ("Flame", Some("fire")),
  ("Tv", Some("tv")),
  ("Filter", Some("filter")),
  ("Box", Some("box")),
  ("Star", Some("star")),
  ("Building2", Some("building")),
  ("FileText", Some("file-text")),
  ("ArrowUpDown", Some("sort-vertical")),
  ("Network", None),
  ("Plus", Some("plus")),
  ("Minus", Some("minus")),
  ("ChevronLeft", Some("chevron-left")),
  ("ChevronRight", Some("chevron-right")),
  ("Calendar", Some("calendar")),
  ("Clock", Some("clock")),
];

/// 手绘图标：24×24 里画 12×12 字符画，放大 2 倍落在网格上（与 pixelarticons 的 2px 像素格一致）。
/// `#` = 实心，`.` = 空。
pub const HAND_ICONS: &[(&str, [&str; 12])] = &[
  (
    "CheckCircle",
    [
      "..########..",
      ".##......##.",
      "##........##",
      "#.......#.##",
      "#......##..#",
      "#.#...##...#",
      "#..#.##....#",
      "#...###....#",
      "##...#....##",
      ".##......##.",
      "..########..",
      "............",
    ],
  ),
  (
    "CheckCircle2",
    [
      "...######...",
      "..##....##..",
      ".#........#.",
      "#.......#..#",
      "#......##..#",
      "#.#...##...#",
      "#..#.##....#",
      ".#..##....#.",
      "..##....##..",
      "...######...",
      "............",
      "............",
    ],
  ),
  (
    "XCircle",
    [
      "...######...",
      "..##....##..",
      ".#.#....#.#.",
      "#...#..#...#",
      "#....##....#",
      "#....##....#",
      "#...#..#...#",
      ".#.#....#.#.",
      "..##....##..",
      "...######...",
      "............",
      "............",
    ],
  ),
  (
    "Satellite",
    [
      "....####....",
      ".....##.....",
      ".....##.....",
      "###.####.###",
      "###.####.###",
      "############",
      "############",
      "###.####.###",
      "###.####.###",
      "............",
      "............",
      "............",
    ],
  ),
  (
    "RadioTower",
    [
      "#....##....#",
      "#..#.##.#..#",
      "#.#..##..#.#",
      "#.#..##..#.#",
      "#..#.##.#..#",
      "#....##....#",
      ".....##.....",
      "....####....",
      "...##..##...",
      "..##....##..",
      ".##......##.",
      "##........##",
    ],
  ),
  (
    "Orbit",
    [
      "....####....",
      "..##....##..",
      ".#..####..#.",
      "#..##..##..#",
      "#.##....##.#",
      "#.#..##..#.#",
      "#.#..##..#.#",
      "#.##....##.#",
      "#..##..##..#",
      ".#..####..#.",
      "..##....##..",
      "....####....",
    ],
  ),
  (
    "ListX",
    [
      "............",
      "##.#######..",
      "............",
      "##.#######..",
      "............",
      "##.####..#.#",
      "...........#",
      "..........#.",
      "......#..#.#",
      "...........#",
      "..........#.",
      "............",
    ],
  ),
  (
    "GraduationCap",
    [
      ".....##.....",
      "...######...",
      ".##########.",
      "############",
      ".##########.",
      "...######...",
      "..#.####.#..",
      "..#..##..#..",
      "..#......#..",
      "..#.....##..",
      "..#.........",
      "............",
    ],
  ),
  (
    "Mountain",
    [
      "............",
      "............",
      "......##....",
      ".....####...",
      "....######..",
      "...###..###.",
      "..###....###",
      ".###......##",
      "###.........",
      "#...........",
      "............",
      "............",
    ],
  ),
  (
    "Plane",
    [
      ".....##.....",
      ".....##.....",
      "....####....",
      "....####....",
      "############",
      "############",
      "....####....",
      "....####....",
      "....####....",
      "...######...",
      "...######...",
      "............",
    ],
  ),
  (
    "Type",
    [
      "############",
      "############",
      "....####....",
      "....####....",
      "....####....",
      "....####....",
      "....####....",
      "....####....",
      "....####....",
      "....####....",
      "............",
      "............",
    ],
  ),
  (
    "Workflow",
    [
      "####........",
      "#..#........",
      "#..#........",
      "####........",
      "..##........",
      "..##########",
      "..#........#",
      "..#.....####",
      "..#.....#...",
      "..#######...",
      "............",
      "............",
    ],
  ),
  (
    "Network",
    [
      ".....##.....",
      "....####....",
      ".....##.....",
      ".....##.....",
      "####.##.####",
      "#..######..#",
      "####.##.####",
      ".....##.....",
      "...######...",
      "...#....#...",
      "...######...",
      "............",
    ],
  ),
];

/// 精灵调色板：字符 → 颜色。
///
/// 用 CSS 变量名而不是写死颜色的只有描边 `K`：亮暗主题切换时描边自动换色。
/// 约定：`K` 描边、`W` 高光（白），其余见下表。
pub const PALETTE: &[(char, &str)] = &[
  ('K', "var(--px-sprite-ink,#1a1c2c)"),
  ('W', "#f4f4f4"),
  ('g', "#94b0c2"),
  ('d', "#566c86"),
  ('R', "#b13e53"),
  ('r', "#ef7d57"),
  ('Y', "#ffcd75"),
  ('y', "#ffe9a8"),
  ('G', "#38b764"),
  ('l', "#a7f070"),
  ('B', "#3b5dc9"),
  ('b', "#41a6f6"),
  ('C', "#73eff7"),
  ('P', "#5d275d"),
  ('p', "#b13e8a"),
  ('S', "#f4c9a0"),
  ('n', "#8b5a3c"),
];

/// 全部精灵：角色 / Boss / 怪物 / 成就徽章 / 地图节点。必须是正方形（行数 = 每行字符数）。
pub const SPRITES: &[(&str, &[&str])] = &[
  (
    "hero",
    &[
      "................",
      ".....KKKKKK.....",
      "....KBBBBBBK....",
      "...KBBBBBBBBK...",
      "..KKKSSSSSSKKK..",
      "..KgKSKSSKSKgK..",
      "..KgKSSSSSSKgK..",
      "..KKKSSRRSSKKK..",
      "....KKSSSSKK....",
      "...KbbbbbbbbK...",
      "..KbbWbbbbWbbK..",
      "..KSKbbbbbbKSK..",
      "...K.KbbbbK.K...",
      "....KBBKKBBK....",
      "....KKK..KKK....",
      "................",
    ],
  ),
  (
    "mon_static",
    &[
      "................",
      "....K..KK..K....",
      "...KgK.KK.KgK...",
      "..KgggKggKgggK..",
      ".KgggggggggggK..",
      ".KggWKgggKWggK..",
      ".KggKKgggKKggK..",
      ".KgggggggggggK..",
      "..KggRRRRRRggK..",
      "..KgggRKKRgggK..",
      "...KgggRRgggK...",
      "..K.KKgggKKK.K..",
      ".K..K.KKKK.K..K.",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "mon_swr",
    &[
      "................",
      "..KK........KK..",
      ".KRRK..KK..KRRK.",
      "KRrrRKKRRKKRrrRK",
      "KRrWRRRRRRRRWrRK",
      ".KRRRKKRRKKRRRK.",
      "..KKK.KRRK.KKK..",
      "......KRRK......",
      "......KRRK......",
      "..KK..KRRK..KK..",
      ".KRRK.KRRK.KRRK.",
      "KRrrRKKRRKKRrrRK",
      "KRrrRRRRRRRRrrRK",
      ".KRRRKKKKKKRRRK.",
      "..KKK......KKK..",
      "................",
    ],
  ),
  (
    "mon_noise",
    &[
      "................",
      "................",
      "......KKKK......",
      "....KKGGGGKK....",
      "...KGGlGGGGGK...",
      "..KGGlGGGGWGGK..",
      "..KGGGGGGGGGGK..",
      ".KGGWKGGGGKWGGK.",
      ".KGGKKGGGGKKGGK.",
      ".KGGGGGGGGGGGGK.",
      ".KGGGGKKKKGGGGK.",
      ".KGGGGGGGGGGGGK.",
      "..KGGGGGGGGGGK..",
      "...KKGGGGGGKK...",
      ".....KKKKKK.....",
      "................",
    ],
  ),
  (
    "mon_spur",
    &[
      "................",
      "K............K..",
      "KK..........KK..",
      "KPK..K..K..KPK..",
      "KPPKKPKKPKKPPK..",
      "KPPPPPPPPPPPPK..",
      ".KPPKWPPWKPPK...",
      ".KPPPPPPPPPPK...",
      "..KPPPRRPPPK....",
      "...KPPKKPPK.....",
      "....KKPPKK......",
      ".....KKKK.......",
      "................",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "mon_fade",
    &[
      "................",
      "....KKKKKK......",
      "...KWWWWWWK.....",
      "..KWWWWWWWWK....",
      "..KWKKWWKKWK....",
      "..KWKBWWKBWK....",
      "..KWWWWWWWWK....",
      "..KWWWKKWWWK....",
      "..KWWWWWWWWK....",
      "..KWWWWWWWWK....",
      "..KWWWWWWWWK....",
      "..KWKWWKWWKK....",
      "..KK.KKK.KK.....",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "boss",
    &[
      "..K..........K..",
      ".KRK........KRK.",
      ".KRRK......KRRK.",
      "..KRRKKKKKKRRK..",
      "..KRRRRRRRRRRK..",
      ".KRRRRRRRRRRRRK.",
      ".KRRWWKRRKWWRRK.",
      ".KRRWKKRRKKWRRK.",
      ".KRRRRRRRRRRRRK.",
      ".KRRKRRRRRRKRRK.",
      ".KRRKWKWKWKWKRK.",
      "..KRRKKKKKKRRK..",
      "...KRRRRRRRRK...",
      "..KKKRRRRRRKKK..",
      ".KYYKKRRRRKKYYK.",
      "..KKK.KKKK.KKK..",
    ],
  ),
  (
    "badge_star",
    &[
      "................",
      ".......KK.......",
      ".......KK.......",
      "......KYYK......",
      "KKKKKKKYYKKKKKKK",
      ".KYYYYYYYYYYYYK.",
      "..KYYYYYYYYYYK..",
      "...KYYWYYYYYK...",
      "...KYYYYYYYYK...",
      "..KYYYYYYYYYYK..",
      "..KYYYKKKKYYYK..",
      ".KYYYK....KYYYK.",
      ".KYYK......KYYK.",
      "..KK........KK..",
      "................",
      "................",
    ],
  ),
  (
    "badge_medal",
    &[
      "................",
      "...KBBK..KRRK...",
      "...KBBK..KRRK...",
      "....KBBKKRRK....",
      ".....KBBRRK.....",
      "......KKKK......",
      "....KKYYYYKK....",
      "...KYYyyYYYYK...",
      "..KYYyYYYYYYYK..",
      "..KYYyYYKKYYYK..",
      "..KYYYYKYYKYYK..",
      "..KYYYYYKYKYYK..",
      "...KYYYYYYYYK...",
      "....KKYYYYKK....",
      "......KKKK......",
      "................",
    ],
  ),
  (
    "badge_trophy",
    &[
      "................",
      "..KKKKKKKKKKKK..",
      ".KYYYYYYYYYYYYK.",
      "KKYyYYYYYYYYYYKK",
      "K.KYyYYYYYYYYK.K",
      "K.KYyYYYYYYYYK.K",
      ".KKYYYYYYYYYYKK.",
      "..KKYYYYYYYYKK..",
      "...KKYYYYYYKK...",
      ".....KKYYKK.....",
      "......KYYK......",
      "......KYYK......",
      "....KKYYYYKK....",
      "...KYYYYYYYYK...",
      "...KKKKKKKKKK...",
      "................",
    ],
  ),
  (
    "badge_flame",
    &[
      "................",
      ".......KK.......",
      "......KRRK......",
      "......KRRRK.....",
      ".....KRRrRK.....",
      "....KRRrrRRK....",
      "...KRRrrYrRRK...",
      "...KRrrYYYrRK...",
      "..KRRrYYYYrRRK..",
      "..KRRrYYWYrRRK..",
      "..KRRrYYYYrRRK..",
      "..KRRRrYYrRRRK..",
      "...KRRRrrRRRK...",
      "....KKRRRRKK....",
      "......KKKK......",
      "................",
    ],
  ),
  (
    "badge_antenna",
    &[
      "................",
      "..K..........K..",
      ".K.K........K.K.",
      "K.K.K..KK..K.K.K",
      "K.K.K..KK..K.K.K",
      ".K.K...KK...K.K.",
      "..K....KK....K..",
      "......KddK......",
      "......KddK......",
      "......KddK......",
      ".....KddddK.....",
      "....KddddddK....",
      "...KddddddddK...",
      "..KKKKKKKKKKKK..",
      "................",
      "................",
    ],
  ),
  (
    "badge_globe",
    &[
      "................",
      "....KKKKKKKK....",
      "...KBBGGBBBBK...",
      "..KBGGGGBBBBBK..",
      ".KBBGGGBBBGGBBK.",
      ".KBBBGGBBGGGBBK.",
      ".KBBBBBBBGGGBBK.",
      ".KBGGBBBBGGBBBK.",
      ".KBGGGBBBBBBBBK.",
      ".KBBGGBBBBGGBBK.",
      ".KBBBBBBBGGGBBK.",
      "..KBBBBBBGGBBK..",
      "...KBBBBBBBBK...",
      "....KKKKKKKK....",
      "................",
      "................",
    ],
  ),
  (
    "badge_book",
    &[
      "................",
      "................",
      "..KKKKKK.KKKKKK.",
      ".KBBBBBKKBBBBBK.",
      ".KBWWWBKKBWWWBK.",
      ".KBBBBBKKBBBBBK.",
      ".KBWWWBKKBWWWBK.",
      ".KBBBBBKKBBBBBK.",
      ".KBWWWBKKBWWWBK.",
      ".KBBBBBKKBBBBBK.",
      ".KKKKKKKKKKKKKK.",
      "................",
      "................",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "badge_log",
    &[
      "................",
      "..KKKKKKKKKK....",
      "..KWWWWWWWWKK...",
      "..KWKKKKKKWKWK..",
      "..KWWWWWWWWKKWK.",
      "..KWKKKKKKWKWWK.",
      "..KWWWWWWWWKWWK.",
      "..KWKKKKWWWKWWK.",
      "..KWWWWWWWWKWWK.",
      "..KWKKKKKKWKWWK.",
      "..KWWWWWWWWKWWK.",
      "..KKKKKKKKKKWWK.",
      ".......KnnnnnK..",
      "........KKKKK...",
      "................",
      "................",
    ],
  ),
  (
    "badge_lock",
    &[
      "................",
      "......KKKK......",
      ".....Kddddd.....",
      "....KdKKKKdK....",
      "....KdK..KdK....",
      "....KdK..KdK....",
      "..KKKKKKKKKKKK..",
      "..KYYYYYYYYYYK..",
      "..KYYYYKKYYYYK..",
      "..KYYYYKKYYYYK..",
      "..KYYYYYKYYYYK..",
      "..KYYYYYYYYYYK..",
      "..KKKKKKKKKKKK..",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "node_flag",
    &[
      "................",
      "..KK............",
      "..KRKK..........",
      "..KRRRKK........",
      "..KRRRRRKK......",
      "..KRRRRRRRK.....",
      "..KRRRRRKK......",
      "..KRRRKK........",
      "..KRKK..........",
      "..KK............",
      "..Kn............",
      "..Kn............",
      "..Kn............",
      ".KKnKK..........",
      "................",
      "................",
    ],
  ),
  (
    "node_heart",
    &[
      "................",
      "................",
      "..KKKK..KKKK....",
      ".KRRRRKKRRRRK...",
      "KRRWWRRRRRRRRK..",
      "KRRWRRRRRRRRRK..",
      "KRRRRRRRRRRRRK..",
      ".KRRRRRRRRRRK...",
      "..KRRRRRRRRK....",
      "...KRRRRRRK.....",
      "....KRRRRK......",
      ".....KRRK.......",
      "......KK........",
      "................",
      "................",
      "................",
    ],
  ),
  (
    "node_coin",
    &[
      "................",
      "................",
      ".....KKKKKK.....",
      "...KKYYYYYYKK...",
      "..KYYyyYYYYYYK..",
      "..KYyYYKKYYYYK..",
      ".KYYyYKYYKYYYYK.",
      ".KYYYYKYYKYYYYK.",
      ".KYYYYKYYKYYYYK.",
      ".KYYYYKKKKYYYYK.",
      "..KYYYYKYYYYYK..",
      "..KYYYYYYYYYYK..",
      "...KKYYYYYYKK...",
      ".....KKKKKK.....",
      "................",
      "................",
    ],
  ),
];
